### ISSUE TITLE
Patrones de diseño: Abstract Factory y Chain Of Responsability

### ISSUE THREAD

**Issue by DavidAlex99** [AdrianLZD/SuperMarioBrosInJava#1]
Buenas. Tengo unas sugerencias para implementar patrones en el codigo. De esta manera por un posible mantenimiento, para que sea mucho mas, ademas permitiendo la escabilidad. Te puedo ayudar con un pdf en donde se encuentran mis recomendacion en la aplicacion de patrones Chain Of responsability y Abstract Factory
[doc patrones aplicados.pdf](https://github.com/AdrianLZD/SuperMarioBrosInJava/files/6927619/doc.patrones.aplicados.pdf)

**Comment by AdrianLZD** [comment]
Hola David, lo siento por la respuesta tardía…

1. En cuanto a los enemigos:
En pocas palabras, sí. La lógica de los enemigos necesitaba estar separada en sus propias clases y manejar la creación de ellos debía ser trabajo de una clase padre. El diseño previo fue hecho con la pura intención de funcionalidad y no de escalabilidad (el hecho de que los métodos de tick retornaran un booleano ni siquiera debió haber ocurrido…).  Tome la idea principal del documento que me compartiste y realice ciertas modificaciones en base a estas; sin embargo al momento de la implementación elegí modificar 2 partes del diseño que me compartiste:
- No se creo la clase "Creator", la creación de los enemigos se maneja en la clase Enemy, la cual ahora es abstracta, por lo que esta no puede ser instanciada por si sola. Se debe llamar un constructor que herede de esta.
- Al convertir la clase Enemy en abstracta, se creó un método abstracto para el tick, por lo que la interfaz no fue necesaria para detallar y asegurar que dicho método sea implementado dentro de cada enemigo.

2. En cuanto a Chain of Responsability:
Para este tema creo entender el problema que se intenta solucionar; sin embargo, la lógica de Mario en cada uno de sus estados actuales es la misma y se maneja en una clase aparte, debido a esto el hecho de crear una clase para cada uno de los estados parece innecesario. Los métodos que señalaste en el documento únicamente cambian la estética de Mario, la cual creo que es el verdadero problema. En algún punto de la implementación se comenzó a manejar las animaciones/estética dentro de la clase que expondría el objeto Mario a todas las demás, por lo que dicha clase terminó realizando dos funciones en vez de una. Actualmente se tiene MarioController.java, la cual maneja el compartamiento de Mario en base al input y Mario.java, esta es la cual probablemente su funcionalidad deba ser revaluada.
En cuanto a este tema no he realizado modificaciones en la implementación, ya que implica una disección muy detallada de las clases y múltiples horas de probar que las animaciones no se rompan; no obstante, es un cambio que deberá ser retomado en caso de proseguir a agregar más funcionalidad.

**Comment by DavidAlex99** [comment]
Yo te tengo que agradecer amigo, gracias de todas maneras por darme una retroalimentacion de mi propuesta

**Comment by AdrianLZD** [comment]
Gracias a ti por las ideas! Cualquier otra propuesta no dudes en compartirla

Cierro el issue.
